### ISSUE TITLE
npm run dev 报错，新人求解。

### ISSUE THREAD

**Issue by wuwenyuan111** [bailicangdu/vue2-happyfri#43]
$ npm run dev

> happyfri@1.0.2 dev I:\workspace\WebStorm\vue2-happyfri
> node build/dev-server.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (I:\workspace\WebStorm\vue2-happyfri\build\dev-server.js:5:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! happyfri@1.0.2 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the happyfri@1.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\FXBL-PC\AppData\Roaming\npm-cache\_logs\2017-11-23T16_57_23_461Z-debug.log

**Comment by wuwenyuan111** [comment]
npm install -d

**Comment by wuwenyuan111** [comment]
Nevermind. I solved it myself.
