### ISSUE TITLE
npm run dev 后报错

### ISSUE THREAD

**Issue by ywlearn** [bailicangdu/vue2-happyfri#49]
直接下载后
npm install后提示deprecate autoprefixer-loader@^3.2.0 ，deprecate babel-preset-es2015@^6.0.0
npm run dev 后有抛出错误
 happyfri@1.0.2 dev C:\Users\gaof\Desktop\VUE\vue2-happyfri-master
> node build/dev-server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:8088
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (C:\Users\gaof\Desktop\VUE\vue2-happyfri-master\node_modules\_express@4.16.2@express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\gaof\Desktop\VUE\vue2-happyfri-master\build\dev-server.js:70:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! happyfri@1.0.2 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the happyfri@1.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gaof\AppData\Roaming\npm-cache\_logs\2017-12-19T07_46_57_968Z-debug.log
请问下这里是需要更新什么吗 新手表示没看懂错误，请大神解惑

**Comment by ywlearn** [comment]
是端口被占用了 我把8088改为其他的 已经解决了
