### ISSUE TITLE
npm run dev 后报错Module build failed: Error: emitFile is required from module system

### ISSUE THREAD

**Issue by zczhoucong** [bailicangdu/vue2-happyfri#98]
ERROR in ./src/images/4-2.png
Module build failed: Error: emitFile is required from module system
    at Object.module.exports (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/file-loader/index.js:9:27)
    at Object.loader (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/url-loader/dist/index.js:76:19)
 @ ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-5aa333df!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/page/score/index.vue 6:215-246

ERROR in ./src/images/4-4.png
Module build failed: Error: emitFile is required from module system
    at Object.module.exports (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/file-loader/index.js:9:27)
    at Object.loader (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/url-loader/dist/index.js:76:19)
 @ ./~/vue-loader/lib/template-compiler.js?id=data-v-5aa333df!./~/vue-loader/lib/selector.js?type=template&index=0!./src/page/score/index.vue 42:13-44

ERROR in ./src/images/1-2.png
Module build failed: Error: emitFile is required from module system
    at Object.module.exports (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/file-loader/index.js:9:27)
    at Object.loader (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/url-loader/dist/index.js:76:19)
 @ ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-40dc09df!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/itemcontainer.vue 6:701-729

ERROR in ./src/images/1-1.jpg
Module build failed: Error: emitFile is required from module system
    at Object.module.exports (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/file-loader/index.js:9:27)
    at Object.loader (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/url-loader/dist/index.js:76:19)
 @ ./~/css-loader!./~/less-loader!./src/style/common.less 6:938-966

ERROR in ./src/images/4-1.jpg
Module build failed: Error: emitFile is required from module system
    at Object.module.exports (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/file-loader/index.js:9:27)
    at Object.loader (/Applications/MAMP/htdocs/github-vue-project/vue2-happyfri/node_modules/url-loader/dist/index.js:76:19)
 @ ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-5aa333df!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/page/score/index.vue 6:64-95
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0
webpack: Failed to compile.

**Comment by lucky-yangyi** [comment]
npm install --force

**Comment by kokakyo** [comment]
收到。
